#!/usr/bin/env python
# -*- coding: utf-8 -*-

#QUESTION :Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#  By starting with 1 and 2, the first 10 terms will be:
#                        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#find the sum of the even-valued terms.
fibonacci=2
i=1
temp=0
sonuc=0
while fibonacci<4000000:
    if fibonacci%2==0:
        sonuc+=fibonacci
    temp=fibonacci
    fibonacci+=i
    i=temp

print(sonuc)
